kind: pipeline
name: svelte-website

steps:
- name: build-svelte-site  
  image: plugins/docker
  settings:
    dockerfile: svelte-site.dockerfile
    username: 
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: registry.alexxnb.ru/svelte-site
    registry: registry.alexxnb.ru
    tags: latest
- name: build-svelte-native-site  
  image: plugins/docker
  settings:
    dockerfile: svelte-native-site.dockerfile
    username: 
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: registry.alexxnb.ru/svelte-native-site
    registry: registry.alexxnb.ru
    tags: latest
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: miniserver.alexxnb.ru
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
    script:
      - docker container stop Svelte-Site
      - docker rm Svelte-Site
      - docker pull registry.alexxnb.ru/svelte-site:latest
      - docker run -d --name Svelte-Site --restart always -p 3000:3000 registry.alexxnb.ru/svelte-site:latest
      - docker container stop Svelte-Native-Site
      - docker rm Svelte-Native-Site
      - docker pull registry.alexxnb.ru/svelte-native-site:latest
      - docker run -d --name Svelte-Native-Site --restart always -p 3001:3000 registry.alexxnb.ru/svelte-native-site:latest