kind: pipeline
name: svelte-websites

steps:

- name: upload docker-compose.yml
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
    target: /tmp/svelte-translate
    source: 
      - ./deploy/docker-compose.yml
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
    command_timeout: 300
    script:
      - cd /tmp/svelte-translate/deploy
      - docker-compose pull
      - docker-compose up --detach --force-recreate
      - rm -rf /tmp/svelte-translate