kind: pipeline
name: svelte-website

steps:
- name: merging-to-svelte-site
  image: node:alpine
  commands:
  - apk add git
  - npm install -g degit
  - mkdir playground && cd playground
  - mkdir svelte
  - degit sveltejs/svelte svelte
  - mv svelte/site web
  - cp -r ../svelte/site/* web/
  - cd web
  - npm install -D locate-character
  - npm ci && npm run update
