kind: pipeline
name: svelte-website

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: registry.alexxnb.ru/svelte-site
    registry: registry.alexxnb.ru
    tags: latest
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: miniserver.alexxnb.ru
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
    script:
      - docker container stop Svelte-Site
      - docker pull registry.alexxnb.ru/svelte-site:latest
      - docker run -d --name Svelte-Site --restart always -p 3000:3000 registry.alexxnb.ru/svelte-site:latest